### PR TITLE
Add console commands for index settings

### PR DESCRIPTION
**Pull request by timkelty**
Adds `scout/index/update-settings` and `scout/index/dump-settings`.

I wanted to have these settings sourced, and also needed the ability to `forwardToReplicas`, which you can't do via the Algolia admin, only the API.

### CODE REVIEW

**Comment by timkelty** [comment]
Hrmmmm looks like the StyleCI failed, but I don't see a `.styleci.yml`, so I don't know what standards I'm up against…my whitespace stuff should just be standard PSR2.

**Comment by timkelty** [comment]
This could just as easily be in it's own `indexSettings` config, instead of nested within the `mappings`…which might make more sense.

**Comment by Rias500** [comment]
@timkelty If you have time, could you look this over again, solve the merge conflicts and add an example use case to the README?

Seems like a great feature to have

**Comment by Rias500** [comment]
@timkelty Merged it in, works great!

**Comment by timkelty** [comment]
@Rias500 oh good! I never updated this to use a separate indexSettings key, which I think is probably still the better choice. Next time I'm in there I'll try and push something.

**Pull request merged**
